FROM golang:1.26

WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends git ca-certificates && rm -rf /var/lib/apt/lists/*

COPY . .

RUN go mod download

CMD ["sh", "-c", "go test ./..."]
